#!/usr/bin/env python3
"""Generate the checked-in example run and its Markdown report.

Produces, relative to the repository root:

    examples/data/example_simulation.csv   a sampled copy of the run
    examples/plots/*.png                   aggregate + per-source figures
    examples/example_report.md             the human-readable report

Run with::

    python scripts/generate_example_report.py
"""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

import matplotlib  # noqa: E402
matplotlib.use("Agg")

from hybridharvest import __version__  # noqa: E402
from hybridharvest.reporting import plot_all_source_details, plot_results  # noqa: E402
from hybridharvest.simulation import run_simulation  # noqa: E402
from hybridharvest.sources import SOURCES  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
EXAMPLES = os.path.join(ROOT, "examples")
DATA_DIR = os.path.join(EXAMPLES, "data")
PLOTS_DIR = os.path.join(EXAMPLES, "plots")

HOURS = 24.0
DT = 1.0
SEED = 42

#: The report and plots are computed from the full-resolution run, but the
#: checked-in CSV keeps only every Nth sample. Writing all 86,400 rows would
#: add ~11 MB to the repository for data that regenerates in a few seconds.
#: Downstream code infers the timestep from the time column, so the sampled
#: file stays internally consistent.
CSV_STRIDE = 60


def write_sampled_csv(result, path: str, stride: int) -> float:
    """Write every ``stride``-th sample of ``result`` to ``path``.

    Parameters
    ----------
    result : SimulationResult
        The full-resolution run.
    path : str
        Destination CSV path.
    stride : int
        Sampling interval, in steps.

    Returns
    -------
    float
        The effective timestep of the written file, in seconds.
    """
    import csv

    source_ids = [sid for sid in SOURCES if sid in result.sources]
    header = ["time_s"]
    header += [f"{sid}_W" for sid in source_ids]
    header += ["total_W", "storage_V", "soc", "load_W"]

    columns = [result.time[::stride]]
    columns += [result.sources[sid].power[::stride] for sid in source_ids]
    columns += [
        result.total_power[::stride],
        result.storage_voltage[::stride],
        result.soc[::stride],
        result.load_power[::stride],
    ]

    with open(path, "w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(header)
        for row in zip(*columns):
            writer.writerow(row)

    times = result.time[::stride]
    return times[1] - times[0] if len(times) > 1 else 0.0


def main() -> int:
    os.makedirs(DATA_DIR, exist_ok=True)
    os.makedirs(PLOTS_DIR, exist_ok=True)

    result = run_simulation(
        duration_hours=HOURS, dt=DT, seed=SEED, enable_solar=True
    )

    csv_path = os.path.join(DATA_DIR, "example_simulation.csv")
    sample_dt = write_sampled_csv(result, csv_path, CSV_STRIDE)
    plot_results(result, PLOTS_DIR)
    plot_all_source_details(result, PLOTS_DIR)

    source_wh = result.source_energy_wh(DT)
    total_wh = result.total_energy_wh(DT)
    load_wh = sum(result.load_power) * DT / 3600.0

    # -- Per-source contribution table ------------------------------------
    rows = []
    for series in result.sources.values():
        rows.append(
            f"| {series.icon} {series.label} "
            f"| {series.peak_power():,.4f} "
            f"| {series.mean_power():,.4f} "
            f"| {series.total_energy_wh(DT):,.4f} "
            f"| {series.share_pct(source_wh, DT):,.2f} |"
        )
    table = "\n".join(rows)

    dominant = max(result.sources.values(), key=lambda s: s.total_energy_wh(DT))
    soc_min, soc_max = min(result.soc), max(result.soc)
    v_min, v_max = min(result.storage_voltage), max(result.storage_voltage)
    peak_total = max(result.total_power)
    mean_total = sum(result.total_power) / len(result.total_power)

    saturated = soc_max >= 0.999 and soc_min >= 0.999

    # -- Per-category data files table ------------------------------------
    # These are written by scripts/export_categorized_data.py, which runs the
    # same seed/parameters, so the two scripts describe the same example run.
    data_file_rows = []
    for sid, series in result.sources.items():
        data_file_rows.append(
            f"| {series.icon} {series.label} "
            f"| `data/processed/{sid}/example_{sid}_24h.csv` "
            f"| `data/processed/{sid}/stats_{sid}.json` |"
        )
    data_file_table = "\n".join(data_file_rows)

    report = f"""# HybridHarvest — Example Run

Generated by `scripts/generate_example_report.py` with HybridHarvest
v{__version__}. Everything below is reproducible from the command in the last
section.

## Run configuration

| Setting | Value |
|---|---|
| Duration | {HOURS:.0f} hours ({len(result.time):,} steps) |
| Timestep `dt` | {DT} s |
| Random seed | {SEED} |
| Sources | wind, hydro, vibration, piezo, solar |
| Conversion efficiency | 0.85 |
| Storage | 10 F supercapacitor, clamped to 5.5 V |
| Checked-in CSV | every {CSV_STRIDE}th sample ({sample_dt:.0f} s resolution), to keep the repository small |

## Summary

| Metric | Value |
|---|---|
| Energy harvested (after conversion losses) | {total_wh:,.2f} Wh |
| Energy summed across sources (pre-conversion) | {source_wh:,.2f} Wh |
| Load consumed | {load_wh:,.4f} Wh |
| Net energy | {total_wh - load_wh:,.2f} Wh |
| Peak harvested power | {peak_total:,.2f} W |
| Mean harvested power | {mean_total:,.4f} W |
| State of charge range | {soc_min:.3f} – {soc_max:.3f} |
| Storage voltage range | {v_min:.3f} – {v_max:.3f} V |

## Per-Source Contribution

| Source | Peak (W) | Mean (W) | Energy (Wh) | Share (%) |
|---|---|---|---|---|
{table}
| **Total** | — | — | **{source_wh:,.4f}** | **100.00** |

Shares are computed against the sum of all sources, so they add to 100 %.
The *Energy harvested* figure in the summary is lower because it is measured
after the 0.85 conversion efficiency; that difference is the conversion loss.

## Per-Category Data Files

The same run is also exported one category at a time, so each harvester has its
own time series and its own statistics file:

| Source | Time series | Statistics |
|---|---|---|
{data_file_table}

Each CSV carries `time_s`, the source's own driving inputs, `power_W` and
`energy_Wh_cumulative`; each JSON holds the peak, mean, standard deviation,
total energy, share, operating hours and capacity factor, plus the
source-specific extras (`cut_in_hours` for wind, `efficiency` for piezo, and so
on). Regenerate them with:

```bash
python scripts/export_categorized_data.py
```

See [`data/README.md`](../data/README.md) for the full schema.

## Charts

Per-source power, one line per harvester:

![Per-source power](plots/per_source_power.png)

Per-source power as a stacked area — total height is the raw harvest:

![Per-source power stacked](plots/per_source_stacked.png)

Total harvested power after conversion losses:

![Total power](plots/total_power.png)

Storage voltage and state of charge:

![Storage voltage and SoC](plots/storage_voltage_soc.png)

Load versus harvest:

![Load vs harvest](plots/load_vs_harvest.png)

### Individual sources

| Wind | Hydro |
|---|---|
| ![Wind](plots/wind_power.png) | ![Hydro](plots/hydro_power.png) |

| Vibration | Piezo |
|---|---|
| ![Vibration](plots/vibration_power.png) | ![Piezo](plots/piezo_power.png) |

| Solar | |
|---|---|
| ![Solar](plots/solar_power.png) | |

## Observations

- **{dominant.label}** is the largest contributor at
  {dominant.share_pct(source_wh, DT):,.2f} % of the pre-conversion energy.
- The sources span a wide range of scale: the wind turbine peaks at
  {result.sources['wind'].peak_power():,.2f} W while the vibration harvester
  peaks at {result.sources['vibration'].peak_power():,.4f} W. The stacked chart
  is therefore dominated by wind; the per-source charts above are the right
  place to read the smaller contributors.
- Storage state of charge {f"stays saturated at {soc_max:.2f} — the harvest far exceeds the load" if saturated else f"varies between {soc_min:.3f} and {soc_max:.3f}"}.
  The duty-cycled load draws only {load_wh:,.4f} Wh over the whole day, roughly
  {100.0 * load_wh / total_wh if total_wh else 0:.2f} % of what is harvested.
- Solar follows the diurnal curve: zero before 06:00 and after 18:00, peaking
  at local noon.

## Reproduce

```bash
pip install -e ".[dev,ui]"
python scripts/generate_example_report.py
```
"""

    report_path = os.path.join(EXAMPLES, "example_report.md")
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report)

    print(f"[ok] steps: {len(result.time)}")
    print(f"[ok] csv: {csv_path}")
    print(f"[ok] plots: {PLOTS_DIR}")
    print(f"[ok] report: {report_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())